name: PHP Checks

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  checks: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  COMPOSER_NO_INTERACTION: 1
  COMPOSER_PROCESS_TIMEOUT: 0

jobs:
  quality:
    runs-on: ubuntu-latest
    # Files are now in repository root

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, sqlite3, xml, curl, tokenizer, xmlwriter, simplexml
          tools: composer:v2, cs2pr
          coverage: none
      
      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      
      - name: Install dependencies
        run: |
          composer validate --strict
          composer install --prefer-dist --no-progress
          
      - name: Set up vendor binaries
        run: |
          chmod +x ./vendor/bin/phpcbf
          chmod +x ./vendor/bin/phpcs
          chmod +x ./vendor/bin/phpstan
          chmod +x ./vendor/bin/phpstan.phar

      - name: Verify PHPStan config
        run: test -f phpstan.neon || echo "PHPStan config not found"
      
      - name: Run PHPCS Auto-Fix
        if: github.event_name == 'pull_request'
        run: |
          ./vendor/bin/phpcbf --standard=PSR12 --ignore=vendor/*,cache/* .
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git diff --staged --quiet || git commit -m "style: auto-fix code style issues"
          git push
        continue-on-error: true
      
      - name: Run PHPCS Manual Check
        run: |
          ./vendor/bin/phpcs --standard=PSR12 --report=checkstyle --ignore=vendor/*,cache/* . | cs2pr
        continue-on-error: true
      
      - name: Run PHPStan
        run: |
          ./vendor/bin/phpstan analyse --configuration=phpstan.neon --error-format=github --no-progress .
