name: PHP Code Quality Checks

on:
  push:
    branches: [ main ]
    paths:
      - 'php-backend/**'
      - '.github/workflows/php-checks.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'php-backend/**'
      - '.github/workflows/php-checks.yml'

jobs:
  quality:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: php-backend

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, sqlite3
          coverage: none
          tools: composer:v2

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-progress
          composer require --dev squizlabs/php_codesniffer phpstan/phpstan

      - name: Run PHPCS Auto-Fix
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          vendor/bin/phpcbf --standard=PSR12 --ignore=vendor/*,cache/* ./ || true
          git config --global user.email "devin@logbie.com"
          git config --global user.name "Devin AI"
          if [[ -n $(git status --porcelain) ]]; then
            # Configure git with token
            git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
            # Fetch PR branch
            git fetch origin pull/${{ github.event.pull_request.number }}/head:${{ github.head_ref }}
            # Checkout and update branch
            git checkout ${{ github.head_ref }}
            git add .
            git commit -m "style: auto-fix code style issues"
            git push origin HEAD:${{ github.head_ref }}
          fi

      - name: Run PHPCS Manual Check
        run: vendor/bin/phpcs --standard=PSR12 --report=full --colors --ignore=vendor/*,cache/* ./

      - name: Run PHPStan
        run: |
          echo "parameters:
            level: 5
            paths:
              - .
            excludePaths:
              - vendor
              - cache
            checkMissingIterableValueType: false" > phpstan.neon
          vendor/bin/phpstan analyse --no-progress
