name: PHP Code Quality Checks

on:
  push:
    branches: [ main, 'devin/*' ]
    paths:
      - 'php-backend/**'
      - '.github/workflows/php-checks.yml'
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]
    paths:
      - 'php-backend/**'
      - '.github/workflows/php-checks.yml'

permissions:
  contents: write
  pull-requests: write
  checks: write

# Limit concurrent runs of this workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  php-quality:
    name: PHP Quality Checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./php-backend

    # Ensure consistent working directory
    env:
      working-directory: ./php-backend
      COMPOSER_PROCESS_TIMEOUT: 0
      COMPOSER_NO_INTERACTION: 1
      COMPOSER_NO_AUDIT: 1

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, sqlite3
          coverage: none
          tools: composer:v2

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer Dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-progress
          composer require --dev squizlabs/php_codesniffer:^3.7 phpstan/phpstan:^1.10

      - name: Run PHPCS Auto-Fix
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          vendor/bin/phpcbf --standard=PSR12 --ignore=vendor/*,cache/* ./ || true
          git config --global user.email "devin@logbie.com"
          git config --global user.name "Devin AI"
          if [[ -n $(git status --porcelain) ]]; then
            git add .
            git commit -m "style: auto-fix code style issues"
            git push
          fi

      - name: Run PHPCS Manual Check
        run: vendor/bin/phpcs --standard=PSR12 --report=full --colors --ignore=vendor/*,cache/* ./

      - name: Run PHPStan
        run: |
          echo "parameters:
            level: 5
            paths:
              - .
            excludePaths:
              - vendor
              - cache" > phpstan.neon
          vendor/bin/phpstan analyse --no-progress
