name: PHP Code Quality Checks

on:
  push:
    branches: [ main, 'devin/*' ]
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the workflow with debug logging'
        required: false
        default: false
        type: boolean

permissions:
  contents: write
  pull-requests: write
  checks: write

# Limit concurrent runs of this workflow and ensure checks run in order:
# 1. PHPCS Auto-Fix (PRs only)
# 2. PHPCS Manual Check
# 3. PHPStan Analysis
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  php-quality:
    name: PHP Quality Checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./php-backend

    # Ensure consistent working directory and environment
    env:
      COMPOSER_PROCESS_TIMEOUT: 0
      COMPOSER_NO_INTERACTION: 1
      COMPOSER_NO_AUDIT: 1
      PHP_CS_FIXER_IGNORE_ENV: 1

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, sqlite3
          coverage: none
          tools: composer:v2

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer Dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-progress
          composer require --dev squizlabs/php_codesniffer:^3.7 phpstan/phpstan:^1.10

      # Step 1: PHPCS Auto-Fix (only on PRs)
      - name: Run PHPCS Auto-Fix
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "::group::Running PHP CodeSniffer Auto-Fix"
          echo "Attempting to automatically fix PSR-12 coding standard violations..."
          vendor/bin/phpcbf --standard=PSR12 --ignore=vendor/*,cache/* ./ || true
          
          if [[ -n $(git status --porcelain) ]]; then
            echo "Changes detected - committing fixes..."
            git config --global user.email "devin@logbie.com"
            git config --global user.name "Devin AI"
            git add .
            git commit -m "style: auto-fix code style issues"
            git push
            echo "Auto-fixes committed and pushed successfully"
          else
            echo "No auto-fixable issues found"
          fi
          echo "::endgroup::"

      # Step 2: PHPCS Manual Check
      - name: Run PHPCS Manual Check
        run: |
          echo "::group::Running PHP CodeSniffer Manual Check"
          echo "Checking PSR-12 coding standards compliance..."
          if vendor/bin/phpcs --standard=PSR12 --report=full --colors --ignore=vendor/*,cache/* ./; then
            echo "✅ All files comply with PSR-12 coding standards"
          else
            echo "❌ Some files do not comply with PSR-12 coding standards"
            exit 1
          fi
          echo "::endgroup::"

      # Step 3: PHPStan Static Analysis
      - name: Run PHPStan
        run: |
          echo "::group::Running PHPStan Static Analysis"
          echo "Analyzing code with PHPStan level 5..."
          echo "Configuring PHPStan with level 5 analysis..."
          
          # Create PHPStan configuration
          echo "parameters:
            level: 5
            paths:
              - .
            excludePaths:
              - vendor
              - cache
            scanDirectories:
              - vendor/gabordemooij/redbean/RedBeanPHP
            universalObjectCratesClasses:
              - RedBeanPHP\OODBBean
              - PLEPHP\Model\Equipment
              - PLEPHP\Model\Checklist" > phpstan.neon
          
          # Run analysis and capture output
          if vendor/bin/phpstan analyse --no-progress --error-format=github; then
            echo "✅ Static analysis passed with no errors"
            echo "phpstan_status=success" >> $GITHUB_OUTPUT
          else
            echo "❌ Static analysis found issues"
            echo "phpstan_status=failure" >> $GITHUB_OUTPUT
            exit 1
          fi
          echo "::endgroup::"

      - name: Generate Job Summary
        if: always()
        run: |
          echo "# PHP Quality Check Results" >> $GITHUB_STEP_SUMMARY
          echo "## PHPCS Auto-Fix" >> $GITHUB_STEP_SUMMARY
          if [[ -n $(git status --porcelain) ]]; then
            echo "✅ Auto-fixes applied and committed" >> $GITHUB_STEP_SUMMARY
          else
            echo "✅ No auto-fixable issues found" >> $GITHUB_STEP_SUMMARY
          fi
          
          echo "## PHPCS Manual Check" >> $GITHUB_STEP_SUMMARY
          if [[ "${{ job.status }}" == "success" ]]; then
            echo "✅ All files comply with PSR-12" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ Some files do not comply with PSR-12" >> $GITHUB_STEP_SUMMARY
          fi
          
          echo "## PHPStan Analysis" >> $GITHUB_STEP_SUMMARY
          if [[ "${{ steps.phpstan.outputs.phpstan_status }}" == "success" ]]; then
            echo "✅ No static analysis issues found" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ Static analysis found issues" >> $GITHUB_STEP_SUMMARY
          fi
